---
title: "Soc 502: HW4"
output: pdf_document
---

# Instructions
Please answer all questions as completely as possible.  There are multiple parts to this assignment.  Your answers to all parts should be recorded in a single document. **I strongly recommend completing Assignment 4 as a knitted rmarkdown document.** You may knit to html or pdf, or even to word if you prefer, your document should contain complete answers to all questions and include necessary statistics and figures. Submit BOTH your knitted file and your rmarkdown document. To help with that, there’s an rmarkdown version of this document on blackboard. If you opt not to use an rmarkdown document, you may continue to submit a word file with code and figures pasted in. Please also submit an r script with your code. Submit via the Blackboard course webpage by 11:59 pm on the due date indicated at the end of the syllabus. Contact Ian ([ikennedy@uic.edu](ikennedy@uic.edu)) early if you run into problems.   

# Part 1: Generic Problems  
   
Recall that in HW3 you were provided with the following information on the number of hours spent studying per week by a sample of her undergraduate students and a sample of her graduate students.  
  
Undergrads	Grads
----------  -----
4	          14
18          18
11          32
17          25
4	          28
8	          15
22          18
----------  -----  
  
Use these data to assess the argument that average study time for the population of graduate students is greater than the average study time for the population of undergraduates.
1.1 Is this a one-tailed or two tailed test? How do you know?
1.2 If you assume a .05 alpha level, what is the critical value of the test statistic?
1.3 What is the obtained value of the test statistic?
1.4 Based on your results, can you reject the null hypothesis?
1.5 What does this indicate about differences in study times between the two populations? Can you be confident that there is a difference in average study times between the two populations?
1.6 Would your decision from Question 1.4 be different if you used an alpha level of .01? Explain.
1.7 Would your decision from Question 1.4 be different if you changed your decision about whether this is a one- or
two-tailed test? Explain your answer.

# Part 2: Generic R problems
#### REPLACE THIS ####  


# Part 3: Your topic  
  
3.1	State your focal relationship, identifying the focal independent variable and focal dependent variable.   
3.2 Make a two-level categorical version of your focal independent variable. Make sure that it has just two levels or categories (either by collapsing existing categories or by splitting a numeric variable at its median).
3.3 What would be the appropriate way to compare the mean of your focal dependent variable across the two values of your just-made categorical version of your independent variable? 
3.4 Conduct the test you proposed in 3.3:
a. Check the assumptions of your test
b. Formally stating the hypotheses
c. Examining the difference in the sample
d. Identifying the confidence level and the critical value
e. Calculating the test statistic
f. Making a decision about the hypotheses
g. Interpreting the results

  