---
title: "Soc 502: HW3"
output: pdf_document
---

# Instructions
Please answer all questions as completely as possible. There are multiple parts to this assignment. Your answers to all parts should be recorded in a single document. To report work from R, copy and paste the key portions of your session, including relevant code and output, into the same Word or pdf document containing answers to other parts of the assignment. Submit this single document via the Blackboard course webpage by 11:59 pm on the due date indicated at the end of the syllabus. Contact Ian ([ikennedy@uic.edu](ikennedy@uic.edu)) or your TA early if you run into problems. 

# Part 1: Generic Problems  
   
1.1	Suppose that at a large state university, graduate research assistants are paid by the hour.  Data from the personnel office show the distribution of hourly wages paid to graduate students across the campus to be roughly normal with a mean of \$24.00 and a standard deviation of \$7.50.  Determine: 
  
  a.	the percentage of graduate students who earn an hourly wage of \$28 or more.  
  b.	the probability of selecting at random from personnel files a graduate assistant who earns an hourly wage of 
\$30 or more   
  c.	the percentage of graduate students who earn between \$16 and \$24 per hour.  
  d.	the probability of selecting at random from personnel files a graduate assistant who earns between \$16 and \$24 per hour.   
  e.	the percentage of graduate students who earn an hourly wage of \$20 or less.   
  f.	the probability of selecting at random from personnel files a graduate assistant who earns an hourly wage of \$20 or less. 
  g.	the probability of selecting at random from personnel files a graduate assistant who is extreme in either direction – earning either \$13 or below or \$35 or above.  
  h.	the probability of selecting at random from personnel files two graduate assistants whose hourly wages are less than average (mean).  
  i.	the probability of selecting at random from personnel files two graduate assistants whose hourly wages are \$28 or more.  
  j.	the two dollar amounts that define the hourly wages received by the middle 95% of graduate students.  
 
 
1.2	A college instructor collects the following information on the number of hours spent studying per week by a group of her undergraduate students and a group of her graduate students. 
 

Undergrads	Grads
----------  -----
4	          14
18          18
11          32
17          25
4	          28
8	          15
22          18
----------  -----

  a.	Calculate measures of central tendency and variability of hours studied for the two groups and use these statistics to describe the differences between the two groups in terms of levels and diversity of satisfaction. 
  b.	Based on the statistics you’ve calculated, what can you tell about the shape of the distributions for the two groups? 
 
 
1.3 Pretend for the moment that the undergraduate students and graduate students referenced in the previous problem represent random samples of their respective populations.  
  
  a.	Find and interpret a 90% confidence interval and a 95% confidence interval estimating the mean number of hours studied by the population of undergraduate students. 
  b.	Explain why the 90% confidence interval and the 95% confidence interval for undergraduate students are different.  What leads to this difference?  Which of the estimates do you prefer? 
  c.	Compare a 95% confidence interval estimating the mean number of hours studied by the population of undergraduate students to a 95% confidence interval estimating the mean number of hours studied by the population of graduate students.  Based on your results, are you confident that the average amount of time spent studying in the population of undergraduate students is different from the population mean for graduate students?  Explain your answer. 


# Part 2: Generic R problems
  
2.1 Load the covid data from `covid_state_data.csv`. To check the data loaded correctly, create some output that checks the column types, and output that contains examples of each column. These can be in the same output.

2.2 Create appropriate measures of central tendency and variability for these three variables: `earliest_case_month`, `restrictions`, and `total_cases`. Provide a brief interpretation of the measures you calculate. 

# Part 3: Your topic  
  
3.1	State your focal relationship, identifying the focal independent and dependent variables.  [Note: I’ll be asking you to do this on every assignment with the hope that you will continue to revise for clarity and precision with each new iteration]. 
  
3.2	Use R and the data provided for your topic to generate and interpret the appropriate measures of central tendency and variability for your focal independent and dependent variables. Strive to create versions of your variables that will be useful for subsequent analyses by collapsing categories as necessary, accounting for missing values, and transforming the variables in any other ways suggested by your theoretical arguments. Make sure to calculate your measures of central tendency and variability only for the cases that have valid information on all of the variables used in your analysis. 
  