---
title: "Soc 502: HW4"
output: pdf_document
---

# Instructions
Please answer all questions as completely as possible.  There are multiple parts to this assignment.  Your answers to all parts should be recorded in a single document. **I strongly recommend completing Assignment 4 as a knitted rmarkdown document.** You may knit to html or pdf, or even to word if you prefer, your document should contain complete answers to all questions and include necessary statistics and figures. Submit BOTH your knitted file and your rmarkdown document. To help with that, there’s an rmarkdown version of this document on blackboard. If you opt not to use an rmarkdown document, you may continue to submit a word file with code and figures pasted in. Please also submit an r script with your code. Submit via the Blackboard course webpage by 11:59 pm on the due date indicated at the end of the syllabus. Contact Ian ([ikennedy@uic.edu](ikennedy@uic.edu)) early if you run into problems.   

# Part 1: Generic Problems  
   
1.1 Recall that in HW3 you were provided with the following information on the number of hours spent studying per week by a sample of her undergraduate students and a sample of her graduate students.  
  
Undergrads	Grads
----------  -----
4	          14
18          18
11          32
17          25
4	          28
8	          15
22          18
----------  -----  
  
Use these data to assess the argument that average study time for the population of graduate students is greater than the average study time for the population of undergraduates.
a. Is this a one-tailed or two tailed test? How do you know?
b. If you assume a .05 alpha level, what is the critical value of the test statistic?
c. What is the obtained value of the test statistic?
d. Based on your results, can you reject the null hypothesis?
e. What does this indicate about differences in study times between the two populations? Can you be confident that there is a difference in average study times between the two populations?
f. Would your decision from Question 1.4 be different if you used an alpha level of .01? Explain.
g. Would your decision from Question 1.4 be different if you changed your decision about whether this is a one- or
two-tailed test? Explain your answer.

1.2 A researcher, Dr. Phillips, is interested in studying whether people are reluctant to interact with members of certain racial and ethnic groups. She designed an experiment in which students enrolled in a lecture course were asked to choose a discussion group (all meeting at the same time in the same building) based only on the racial/ethnic stereotype associated with the names of the teaching assistant. She observed the following registration counts: 

Teaching Assistant	Students enrolled 
------------------  -----------------
Cheng	                20
Goldberg	            37
Jackson	              24
Smith	                32
Rodriguez	            15
------------------  -----------------

Use one-way chi-square to test the null hypothesis that the racial/ethnic name made no difference in students’ selection of a discussion group. Use a .05 confidence level and provide the following information (showing all calculations):   
  
a.	the degrees of freedom   
b.	the critical value of the test statistic   
c.	the obtained value of the test statistic  
d.	your decision about the null hypothesis and the meaning of this decision  
e.	Are the sample data sufficient to reject the null hypothesis using a .01 confidence level?   
f. If you doubled the count of cases in each of the cells of the table, would you reach the same decision about the hypothesis? Provide the key information used in making your decision?  

# Part 2: Generic R problems
After running through Lab 7, use a chi-squared test in R to assess the statistical significance of the association between GENDER and belief that global warming is a result of human activity. Use the "Environmental Attitudes” data available on the course website (data are called "nsee_modified.Rdata"). Gender is in the variable called "DEMOG_GENDER." For attitudes toward global warming, use the variable "BELIEVER_CAUSE" and differentiate between two categories: 1) those who believe warming is due to human activity (original code = 1); and 2) those who either believe warming is due to natural patterns (original code =2) plus those who believe it is due to  a combination of factors (original code = 3). Make sure to also get rid of any folks who refused to answer or were not asked the question.  

2.1	Does there appear to be an association between gender and attitudes toward the causes of global warming in the sample? Explain your answer by referring to the results of the analysis.   
2.2	Is the association between gender and attitudes toward the causes of global warming statistically significant?  How do you know and what does this mean?   
2.3	Does your answer to Question b depend on the alpha level you use for the test? Why?  


# Part 3: Your topic  
  
3.1	State your focal relationship, identifying the focal independent variable and focal dependent variable.   
3.2 Make a two-level categorical version of your focal independent variable. Make sure that it has just two levels or categories (either by collapsing existing categories or by splitting a numeric variable at its median).
3.3 What would be the appropriate way to compare the mean of your focal dependent variable across the two values of your just-made categorical version of your independent variable? 
3.4 Conduct the test you proposed in 3.3:
a. Check the assumptions of your test
b. Formally stating the hypotheses
c. Examining the difference in the sample
d. Identifying the confidence level and the critical value
e. Calculating the test statistic
f. Making a decision about the hypotheses
g. Interpreting the results

  